apiVersion: v1
description: Helm chart for generic monolithic app on Kubernetes
maintainers:
- name: QJOLY
  email: github@thoughtless.eu
name: common
version: v0.1.7
appVersion: "0"
kubeVersion: ">= 1.18"
home: https://github.com/QJoly/generic-helm-template
keywords:
  - generic
  - monolithic
  - ingress-route
  - ingress
sources:
  - https://github.com/QJoly/generic-helm-template

