{{- if and (.Values.ingress.enabled) (not .Values.ingress.isIngressRoute) }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "nextcloud.fullname" . }}-ingressroute
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
spec:
  entryPoints: 
    - {{ .Values.ingress.entrypoint }}
  routes:
  - match: Host(`{{ .Values.ingress.domain }}`)
    kind: Rule
    services:
    - name: {{ include "nextcloud.fullname" . }}-app
      port: {{ .Values.service.port }}
  tls:
    certResolver: {{ .Values.ingress.certresolver }}
{{- end}}