apiVersion: v2
name: freshrss
description: A WebUI to read article via RSS
type: application
version: 1.0.0
appVersion: "1.21.0"
keywords:
- freshrss
home: https://freshrss.org/
maintainers:
- email: github@thoughtless.eu
  name: QJOLY
  url: https://thebidouilleur.xyz
sources:
- https://github.com/FreshRSS/FreshRSS
- https://github.com/QJoly/helm-charts
dependencies:
  - name: common
    repository: https://qjoly.github.io/helm-charts/
    version: v0.1.0