common:
  app:
    servicePort: 80
    containerPort: 80

  # deployment
  deployment:
    memoryRequest: null
    cpuRequest: null
    memoryLimit: null
    cpuLimit: null
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%

  # container
  image:
    repository:
      name: null
      isPrivate: false
      secretName: null
    name: linuxserver/smokeping
    tag: 2.8.2
    pullPolicy: Always

  # ingress
  ingress:
    enabled: false
    hostName: smokeping.thoughtless.eu
    tls:
      enabled: true
      secretName: ""
    # For Ingress CRD
    ingressClassName: 
    # For IngressRoute CRD
    isIngressRoute: true
    entrypoint: websecure
    certResolver: letsencrypt # leave empty if you don't use, tls.enabled must be true and secretName must me empty

      
  # env variables
  variables:
    secret: {}
  #    user: "qjoly"
  #    password: "hugepassword"
    nonSecret: {}
  #    author: qjoly
  #    app: 1

  # horizontal autoscaler
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    avgCpuUtilization: 50

  # startupProbe
  startupProbe:
    enabled: false
    httpGet:
      path: "/"
    periodSeconds: 10
    failureThreshold: 20
    timeoutSeconds: 1

  # readinessProbe
  readinessProbe:
    enabled: true
    httpGet:
      path: "/"
    initialDelaySeconds: 20
    periodSeconds: 30
    failureThreshold: 2
    timeoutSeconds: 3

  # livenessProbe
  livenessProbe:
    enabled: true
    httpGet:
      path: "/"
    initialDelaySeconds: 20
    periodSeconds: 60
    failureThreshold: 1
    timeoutSeconds: 3

  persistence:
    enabled: true
    volumes:
      - name: "data"
        storageClassName: "" # leave empty if you want to use default
        size: "5Gi" # We recommend to allocate a minimum of 1GB if you do not use attachments
        pvcClaim: "" # leave empty unless if you want to use an existing PVC
        containerMount: "/data/"
      - name: "config"
        storageClassName: "" # leave empty if you want to use default
        size: "1Gi" # We recommend to allocate a minimum of 1GB if you do not use attachments
        pvcClaim: "" # leave empty unless if you want to use an existing PVC
        containerMount: "/config/"
  tests:
    classicHttp: # default helm test method 
      enabled: true
    curlHostHeader: # curl using ingress.hostName as Host in header
      enabled: false
      path: "/"

