---
apiVersion: v2
appVersion: 0.8.0
description: PrezVim is a french presentation to introduce Vim to new users.
name: PrezVim
version: 5.1.2
kubeVersion: ">=1.16.0-0"
keywords:
  - baikal
  - caldav
  - carddav
  - contacts
  - calendar
home: https://vim.avec.une-tasse-de.cafe/
icon: https://avatars.githubusercontent.com/u/28524376?s=400&v=4
sources:
  - https://github.com/sabre-io/Baikal
  - https://github.com/ckulka/baikal-docker
maintainers:
- email: github@thoughtless.eu
  name: QJOLY
  url: https://thebidouilleur.xyz
dependencies:
  - name: common
    repository: https://qjoly.github.io/helm-charts/
    version: v0.1.0