{{- if and (.Values.ingress.enabled) (.Values.ingress.isIngressRoute) }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "pingvin.fullname" . }}
  labels:
    {{- include "pingvin.labels" . | nindent 4 }}
spec:
  entryPoints: {{ .Values.ingress.entrypoint }}
  routes:
  - match: Host(`{{ .Values.ingress.domain }}`)
    kind: Rule
    services:
    - name: {{ include "pingvin.fullname" . }}-app
      port: 22300
  tls:
    certResolver: {{ .Values.ingress.certresolver }}
{{- end}}
