apiVersion: v1
kind: Service
metadata:
  name: {{ include "joplin.fullname" . }}-app
  labels:
    {{- include "joplin.labels" . | nindent 4 }}
spec:
  ports:
    - name: "22300"
      port: 22300
      targetPort: 22300
  selector:
    {{- include "joplin-app.selectorLabels" . | nindent 4 }}
status:
  loadBalancer: {}
