{{- if .Values.persistence.enabled -}}
{{- if not .Values.persistence.pvcClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    {{- include "joplin.labels" . | nindent 4 }}
  name: {{ .Chart.Name }}
spec:
  storageClassName: "longhorn"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
status: {}
{{- end }}
{{- end }}