apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-app
  labels:
    {{- include "joplin.labels" . | nindent 4 }}
spec:
  ports:
    - name: "22300"
      port: 22300
      targetPort: 22300
  selector:
    name: {{ .Chart.Name }}-app
status:
  loadBalancer: {}
