apiVersion: v1
kind: Service
metadata:
  name: {{ include "joplin.fullname" . }}-db
  labels:
    {{- include "joplin.labels" . | nindent 4 }}
spec:
  ports:
    - name: "postgresql"
      port: 5432
      targetPort: {{ .Values.service.database.port }}
  selector:
    {{- include "joplin-db.selectorLabels" . | nindent 8 }}
status:
  loadBalancer: {}
