apiVersion: apps/v1
kind: Deployment
metadata:
  name: joplin-db
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-db
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-db 
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "joplin.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - env:
            - name: POSTGRES_DB
              value: joplin
            - name: POSTGRES_PASSWORD
              value: veryhugepasswordhere
            - name: POSTGRES_USER
              value: joplin
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          image: postgres:15
          name: {{ .Chart.Name }}-db
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              subPath: pgdata
              name: db
      restartPolicy: Always
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: joplin-pvc-db
status: {}
