apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-app
  labels:
    {{- include "joplin.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-app
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-app
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - env:
            - name: APP_BASE_URL
              value: {{ .Values.joplin.base_url }}
            - name: APP_PORT
              value: "22300"
            - name: DB_CLIENT
              value: pg
{{- if .Values.mailer.enabled }}
            - name: MAILER_ENABLED
              value: "1"
            - name: MAILER_HOST
              value: "{{ .Values.mailer.host }}"
            - name: MAILER_NOREPLY_EMAIL
              value: {{ .Values.mailer.noreplymail }}
            - name: MAILER_NOREPLY_NAME
              value: {{ .Values.mailer.noreplyname }}
            - name: MAILER_PORT
              value: "{{ .Values.mailer.port }}"
            - name: MAILER_SECURITY
              value: {{ .Values.mailer.security }}
            - name: MAILER_AUTH_USER
              value: {{ .Values.mailer.user }}
            - name: MAILER_AUTH_PASSWORD
              value: {{ .Values.mailer.password }}
{{- else }}
            - name: MAILER_ENABLED
              value: "0"
{{- end }}
            - name: POSTGRES_DATABASE
              value: {{ .Values.database.dbname }}
            - name: POSTGRES_HOST
              value: {{ .Chart.Name }}-db
            - name: POSTGRES_PASSWORD
              value: {{ .Values.database.dbpassword }}
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: {{ .Values.database.dbuser }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: joplin-app
          ports:
            - containerPort: 22300
          livenessProbe:
            tcpSocket:
              port: 22300
            initialDelaySeconds: 190
          readinessProbe:
            tcpSocket:
              port: 22300
          resources: {}
      restartPolicy: Always
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
status: {}

