replicaCount: 1

image:
  repository: osixia/openldap:1.5.0
  pullPolicy: IfNotPresent
  tag: "1.5.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "openldap"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 389

settings:
  KEEP_EXISTING_CONFIG: "false"
  LDAP_ADMIN_PASSWORD: admin
  LDAP_BACKEND: mdb
  LDAP_BASE_DN: eu
  LDAP_CONFIG_PASSWORD: confighugepass
  LDAP_DOMAIN: thoughtless.eu
  LDAP_LOG_LEVEL: "256"
  LDAP_ORGANISATION: ThoughtlessInc.
  LDAP_READONLY_USER: "false"
  LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
  LDAP_REPLICATION: "false"
  LDAP_RFC2307BIS_SCHEMA: "false"
  LDAP_SSL_HELPER_PREFIX: ldap


resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
