apiVersion: v2
type: application
name: jackett
description: "Jackett works as a proxy server: it translates queries from apps into tracker-site-specific http queries."
version: 1.0.0
appVersion: "0.21.290"
maintainers:
- name: QJOLY
  email: github@thoughtless.eu
kubeVersion: ">= 1.18"
home: https://radarr.video/
keywords:
  - Jackett
  - Plex
  - Series
sources:
  - https://github.com/Jackett/Jackett
dependencies:
  - name: common
    repository: https://qjoly.github.io/helm-charts/
    version: v0.1.8
