apiVersion: v2
name: wakapi
description: Wakapi is an open-source tool that helps you keep track of the time you have spent coding.
version: 1.0.0
appVersion: "2.7"
icon: https://wakapi.dev/assets/images/logo.svg
keywords:
- wakapi
home: https://wakapi.dev/
maintainers:
- email: github@thoughtless.eu
  name: QJOLY
  url: https://thebidouilleur.xyz
sources:
- https://wakapi.dev/
- https://github.com/QJoly/helm-charts
dependencies:
  - name: common
    repository: https://qjoly.github.io/helm-charts/
    version: v0.1.0
  - name: postgresql
    version: 11.6.12
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled