common:
  app:
    servicePort: 80
    containerPort: 3000

  # deployment
  deployment:
    memoryRequest: null
    cpuRequest: null
    memoryLimit: null
    cpuLimit: null
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%

  # container
  image:
    repository:
      name: null
      isPrivate: false
      secretName: null
    name: n1try/wakapi
    tag: 2.7
    pullPolicy: Always

  # ingress
  ingress:
    enabled: false
    hostName: wakapi.lan
    tls:
      enabled: true
      secretName: ""
    # For Ingress CRD
    ingressClassName: istio
    # For IngressRoute CRD
    isIngressRoute: true
    entrypoint: websecure
    certResolver: letsencrypt # leave empty if you don't use, tls.enabled must be true and secretName must me empty

      
  # env variables
  variables:
    secret: {}
    nonSecret:
      WAKAPI_DB_TYPE: "postgres"
      WAKAPI_DB_NAME: "wakapi"
      WAKAPI_DB_USER: "wakapuser"
      WAKAPI_DB_PASSWORD: "wakapass"
      WAKAPI_DB_HOST: "wakapi-postgresql" # if postgresql.enabled, must be RELEASE-NAME-postgresql (ex: my-wakapi-postgresql)
      WAKAPI_DB_PORT: "5432"
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    avgCpuUtilization: 50

  # startupProbe
  startupProbe:
    enabled: false
    httpGet:
      path: "/"
    periodSeconds: 10
    failureThreshold: 20
    timeoutSeconds: 1

  # readinessProbe
  readinessProbe:
    enabled: true
    httpGet:
      path: "/"
    initialDelaySeconds: 20
    periodSeconds: 30
    failureThreshold: 2
    timeoutSeconds: 3

  # livenessProbe
  livenessProbe:
    enabled: true
    httpGet:
      path: "/"
    initialDelaySeconds: 20
    periodSeconds: 60
    failureThreshold: 1
    timeoutSeconds: 3

  persistence:
    enabled: false
    volumes:
      - name: "data"
        storageClassName: "" # leave empty if you want to use default
        size: "5Gi" # We recommend to allocate a minimum of 1GB if you do not use attachments
        pvcClaim: "" # leave empty unless if you want to use an existing PVC
        containerMount: "/data"

postgresql:
  enabled: true
  auth:
    postgresPassword: "changeme"
    database: wakapi
    username: wakapuser
    password: wakapass
  persistence:
    enabled: false
    existingClaim: ""
    storageClass: ""
    # size: 8Gi

