apiVersion: v2
type: application
name: radarr
description: Radarr is a movie collection manager for Usenet and BitTorrent users
version: 1.0.0
appVersion: "4.5.2"
maintainers:
- name: QJOLY
  email: github@thoughtless.eu
kubeVersion: ">= 1.18"
home: https://radarr.video/
keywords:
  - radarr
  - plex
  - movie
  - collection
  - torrent
sources:
  - https://github.com/Radarr/Radarr
dependencies:
  - name: common
    repository: https://qjoly.github.io/helm-charts/
    version: v0.1.8
