apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openldap.fullname" . }}
  labels:
    {{- include "openldap.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "openldap.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openldap.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LDAP_ADMIN_USERNAME
              value: {{ .Values.ldap.admin_username }}
            - name: LDAP_ADMIN_PASSWORD
              value: {{ .Values.ldap.admin_password }}
            - name: LDAP_USERS
              value: {{ .Values.ldap.users }}
            - name: LDAP_PASSWORDS
              value: {{ .Values.ldap.passwords }}
            - name: LDAP_ROOT
              value: {{ .Values.ldap.root }}
            - name: LDAP_USER_DC
              value: {{ .Values.ldap.user_dc }}
          ports:
            - name: ldap
              containerPort: 1389
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 1389
          readinessProbe:
            tcpSocket:
              port: 1389
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
