{{- if .Values.ingress.enabled -}}
{{- if .Values.ingress.isIngressRoute -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Chart.Name }}-ingressroute
  labels:
    {{- include "baikal.labels" . | nindent 4 }}
spec:
  entryPoints: 
    - {{ .Values.ingress.entrypoint }}
  routes:
  - match: Host(`{{ .Values.ingress.domain }}`)
    kind: Rule
    services:
    - name: {{ include "baikal.fullname" . }}
      port: {{ .Values.service.port }}
  tls:
    certResolver: {{ .Values.ingress.certresolver }}
{{- end}}
{{- end}}
