apiVersion: v1
kind: Service
metadata:
  name: {{ include "wakapi.fullname" . }}-app
  labels:
    {{- include "wakapi.labels" . | nindent 4 }}
spec:
  ports:
    - name: "http"
      port: {{ .Values.service.wakapi.port }}
      targetPort: {{ .Values.service.wakapi.port }}
  selector:
    {{- include "wakapi-app.selectorLabels" . | nindent 4 }}
status:
  loadBalancer: {}
