apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wakapi.fullname" . }}-app
  labels:
    {{- include "wakapi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "wakapi-app.selectorLabels" . | nindent 8 }}
  strategy: {}
  template:
    metadata:
      labels:
        {{- include "wakapi-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - env:
        {{- if .Values.database.enabled }}
            - name: WAKAPI_DB_TYPE
              value: "postgres"
            - name: WAKAPI_DB_NAME
              value: {{ .Values.database.dbname }}
            - name: WAKAPI_DB_HOST
              value: {{ include "wakapi.fullname" . }}-db
            - name: WAKAPI_DB_PASSWORD
              value: {{ .Values.database.dbpassword }}
            - name: WAKAPI_DB_PORT
              value: "5432"
            - name: WAKAPI_DB_USER
              value: {{ .Values.database.dbuser }}
        {{- else }}
            - name: WAKAPI_DB_TYPE
              value: "sqlite3"
        {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: wakapi-app
          ports:
            - containerPort: 3000
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 190
          readinessProbe:
            tcpSocket:
              port: 3000
          resources: {}
      restartPolicy: Always
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
status: {}

