apiVersion: v1
kind: Service
metadata:
  name: {{ include "wakapi.fullname" . }}-db
  labels:
    {{- include "wakapi.labels" . | nindent 4 }}
spec:
  ports:
    - name: "postgresql"
      port: {{ .Values.service.database.port }}
      targetPort: {{ .Values.service.database.port }}
  selector:
    {{- include "wakapi-db.selectorLabels" . | nindent 8 }}
status:
  loadBalancer: {}
