{{- if .Values.ingress.enabled -}}
{{- if .Values.ingress.isIngressRoute -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "wakapi.fullname" . }}-ingressroute
  labels:
    {{- include "wakapi.labels" . | nindent 4 }}
spec:
  entryPoints: 
    - {{ .Values.ingress.entrypoint }}
  routes:
  - match: Host(`{{ .Values.ingress.domain }}`)
    kind: Rule
    services:
    - name: {{ include "wakapi.fullname" . }}-app
      port: {{ .Values.service.wakapi.port }}
  tls:
    certResolver: {{ .Values.ingress.certresolver }}
{{- end}}
{{- end}}
