apiVersion: v2
name: joplin
description: Joplin is an open source note-taking app. Capture your thoughts and securely access them from any device. 
version: 1.0.0
appVersion: "2.11-beta"
keywords:
- joplin
home: https://joplinapp.org/
maintainers:
- email: github@thoughtless.eu
  name: QJOLY
  url: https://thebidouilleur.xyz
sources:
- https://github.com/laurent22/joplin
- https://github.com/QJoly/helm-charts
dependencies:
  - name: common
    repository: https://qjoly.github.io/helm-charts/
    version: v0.1.7
  - name: postgresql
    version: 11.6.12
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
