apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
{{- with .Values.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
{{- end }}
  selector:
    {{- include "mosquitto.selectorLabels" . | nindent 4 }}
