apiVersion: v1
name: joplin
description: Joplin is an open source note-taking app. Capture your thoughts and securely access them from any device. 
version: 0.3.8
appVersion: "2.10.10-beta"
keywords:
- joplin
home: https://joplinapp.org/
maintainers:
- email: github@thoughtless.eu
  name: QJOLY
  url: https://thebidouilleur.xyz
sources:
- https://github.com/laurent22/joplin
- https://github.com/QJoly/helm-charts
