apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "epicgames-freegames.fullname" . }}
#  labels:
#    - include "epicgames-freegames.labels" . | nindent 4 
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
    {{- include "epicgames-freegames.selectorLabels" . | nindent 8 }}
  strategy: {}
  template:
    metadata:
      labels:
        {{- include "epicgames-freegames.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: epicgames-freegames-app
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /usr/app/config/config.json
              subPath: config.json
              name: config
      volumes:
        - name: config
          configMap:
            name: {{ include "epicgames-freegames.fullname" . }}

      restartPolicy: Always
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
status: {}

