apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-cm

data:
  config.json: |
    {
    "runOnStartup": true,
    "cronSchedule": "5 16 * * *",
    "logLevel": "info",
    "webPortalConfig": {
      "baseUrl": "{{ .Values.settings.baseUrl }}",
    },
    "accounts": [
      {
        "email": "hello@gmail.com",
        "password": "abc123",
        "totp": "ur_totp"
      },
    ],
    "notifiers": [
{{- if .Values.settings.notifiers.mail.enabled }}
      {
        "type": "email",
        "smtpHost": "",
        "smtpPort": 587,
        "emailSenderAddress": "hello@gmail.com",
        "emailSenderName": "Epic Games Captchas",
        "emailRecipientAddress": "hello@gmail.com",
        "secure": false,
        "auth": {
            "user": "hello@gmail.com",
            "pass": "abc123",
        },
      },
{{- end }}
{{- if .Values.settings.notifiers.discord.enabled }}
      {
        "type": "discord",
        "webhookUrl": "{{ .Values.settings.notifiers.discord.webhookUrl }}",
      },
{{- end }}
{{- if .Values.settings.notifiers.telegram.enabled }}
      {
        "type": "telegram",
        "token": "{{ .Values.settings.notifiers.telegram.token }}",
        "chatId": "{{ .Values.settings.notifiers.telegram.chatid }}",
      },
{{- end }}
{{- if .Values.settings.notifiers.apprise.enabled }}
      {
        "type": "apprise",
        "apiUrl": "{{ .Values.settings.notifiers.apprise.apiUrl }}",
        "urls": "{{ .Values.settings.notifiers.apprise.url }}",
      },
{{- end }}
    ],
    }
