apiVersion: v1
kind: Service
metadata:
  name: {{ include "epicgames-freegames.fullname" . }}
  labels:
    {{- include "epicgames-freegames.labels" . | nindent 4 }}
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    {{- include "epicgames-freegames.selectorLabels" . | nindent 8 }}
status:
  loadBalancer: {}
