
name: Testing charts 
on:  
  pull_request:
    branches:
      - main
jobs:
   testing:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v2
         with:
           fetch-depth: 0

       - uses: azure/setup-helm@v3
         with:
            token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'
       
       - name: Helm Lint
         run: |
           cd .github/workflows/
           ./helm_lint.sh


