name: Release Charts
on:
   push:
     branches:
       - main
jobs:
   release:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v2
         with:
           fetch-depth: 0

       - name: Setup Python
         uses: actions/setup-python@v4.3.0

       - name: Configure Git
         run: |
           git config user.name "$GITHUB_ACTOR"
           git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

       - uses: azure/setup-helm@v3
         with:
            token: ${{ secrets.GITHUB_TOKEN }} 
       
       - name: Helm Lint
         run: |
           cd .github/workflows/
           ./helm_lint.sh

       - name: Create k8s Kind Cluster
         uses: helm/kind-action@v1.3.0
         
       - name: Install kubectl
         uses: Azure/setup-kubectl@v3
         
       - name: Deploy all charts to kind
         run: |
           cd .github/workflows/
           ./helm_deploy.sh

       - name: Run chart-releaser
         uses: helm/chart-releaser-action@v1.4.1
         env:
           CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
           
       - name: Install requirements
         continue-on-error: true
         run: |
          cd .github/workflows/
          python -m pip install -r requirements.txt 
          python3 get_readme.py
          cd ../..
          git add README.md
          git commit -m "[AUTO] Update README with Charts versions"
          git push
