name: Release Charts
on:
   push:
     branches:
       - main
jobs:
   release:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v1
         
       - name: Install Nix
         uses: cachix/install-nix-action@v18
         with:
           nix_path: nixpkgs=channel:nixos-unstable
         
       - name: Run nix-shell and python-script
         run: |
            cd .github/workflows/
            nix-shell
            python3 get_readme.py
         
       - name: Configure Git
         run: |
           git config user.name "$GITHUB_ACTOR"
           git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

       - name: Run chart-releaser
         uses: helm/chart-releaser-action@v1.4.1
         env:
           CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

