name: Release Charts
on:
   push:
     branches:
       - main
jobs:
   release:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v2
         with:
           fetch-depth: 0

       - name: Setup Python
         uses: actions/setup-python@v2.3.3

       - name: Configure Git
         run: |
           git config user.name "$GITHUB_ACTOR"
           git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

       - uses: azure/setup-helm@v3
         with:
            token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'
       
       - name: Helm Lint
         run: |
           cd .github/workflows/
           ./helm_lint.sh

       - name: Run chart-releaser
         uses: helm/chart-releaser-action@v1.4.1
         env:
           CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
           
       - name: Install requirements
         continue-on-error: true
         run: |
          cd .github/workflows/
          python -m pip install -r requirements.txt 
          python3 get_readme.py
          cd ../..
          git add README.md
          git commit -m "[AUTO] Update README with Charts versions"
          git push
