---
name: Testing charts
on:
  push:
    branches:
      - '*'
      - '!main'
  pull_request:
    branches:
      - main
jobs:
  testing:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v2
         with:
           fetch-depth: 0

       - uses: azure/setup-helm@v3
         with:
            token: ${{ secrets.GITHUB_TOKEN }} 
       
       - name: Get changed files in the charts folder
         id: changed-files-specific
         uses: tj-actions/changed-files@v36
         with:
           files: charts

       - name: Create k8s Kind Cluster
         uses: helm/kind-action@v1.5.0
         
       - name: Install kubectl
         uses: Azure/setup-kubectl@v3

       - name: Set up library chart (for dependencies)
         run: |
            helm repo add bitnami https://charts.bitnami.com/bitnami
            helm repo add qjoly https://qjoly.github.io/helm-charts

       - name: Run lint for any chart concerned by the commit
         if: steps.changed-files-specific.outputs.any_changed == 'true'
         run: |
           .github/workflows/lint_modified_charts.sh ${{ steps.changed-files-specific.outputs.all_changed_files }}
 
       - name: Run test for any chart concerned by the commit
         if: steps.changed-files-specific.outputs.any_changed == 'true'
         run: |
           .github/workflows/deploy_modified_charts.sh ${{ steps.changed-files-specific.outputs.all_changed_files }}
 
