replicaCount: 1

image:
  repository: charlocharlie/epicgames-freegames
  pullPolicy: IfNotPresent
  tag: latest

settings: 
  account:
    email: hello@gmail.com
    password: abc123
    totp: bigtotp
  baseUrl: https://ur-domain.tld # 
  notifiers:
    discord:
      enabled: false
      webhookUrl: "https://discordapp.com/api/webhooks/1049231686778867764/dlC39GaS09RKQQJF6bCGJFflswv-vAIVOiCXEdhuHucsgaEQfsi4U0Z-1Vk3Ms"
    mail:
      enabled: false
      host: "smtp.gmail.com"
      port: 587
      emailSenderAddress: hello@gmail.com
      emailSenderName: hello@gmail.com
      emailRecipientAddress: Epic Games Captchas
      secure: false
      auth:
        user: hello@gmail.com
        pass: abc123
    telegram:
      enabled: false
      token: "5536253584:AAEbvjHjPhuFOr5qcBd47a_jj0aggrT7MOc"
      chatid: "359643240"
    apprise:
      enabled: false
      apiUrl: "http://192.168.1.2:8000"
      url: "mailto://user:pass@gmail.com"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


podAnnotations: {}

podSecurityContext: 
  fsGroup: 2000

securityContext: 
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  #  runAsUser: 1000

service:
  type: ClusterIP
  port: 3000

ingress:
  isIngressRoute: false
  enabled: true
  className: ""
  annotations: {}
  domain: ur-domain.tld
  entrypoint: websecure # Useless if you use ingressroute
  certresolver: letsencrypt

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
